server:
  port: 8283

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/RESERVATION-SERVICES?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: RESERVATION-SERVICES



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone: ${EUREKA_SERVER-ADDRESS:http://localhost:8761/eureka}
